FROM debian:buster-slim

# add our user and group first to make sure their IDs get assigned consistently,
# regardless of whatever dependencies get added
RUN groupadd -r edgedns && useradd -r -u 1000 -g edgedns edgedns

#
# Set proper timezone
#
ENV TZ='America/Los_Angeles'


# grab gosu for easy step-down from root (https://github.com/tianon/gosu/releases)
ENV GOSU_VERSION 1.12
ENV EDGEDNS_VERSION=0.2.2

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    apt-get update && \
    apt-get install --no-install-recommends -y \
        ca-certificates \
        net-tools \
        wget && \
    dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
	wget -q "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch" -O /usr/local/bin/gosu && \
	chmod +x /usr/local/bin/gosu && \
    wget -q https://github.com/jedisct1/edgedns/releases/download/${EDGEDNS_VERSION}/edgedns-${EDGEDNS_VERSION}-x86_64-unknown-linux-gnu.tar.gz && \
    tar -xzf edgedns-${EDGEDNS_VERSION}-x86_64-unknown-linux-gnu.tar.gz && \
    rm edgedns-${EDGEDNS_VERSION}-x86_64-unknown-linux-gnu.tar.gz && \
    mv edgedns /usr/sbin/ && \
    apt-get remove -y wget && \
    apt-get autoremove -y

# motd was generated by `figlet`: figlet -f slant "Edge DNS"
COPY etc/motd /etc/motd

# Run Gin in "release" mode in production
ENV GIN_MODE=release
ENV GIN_LOG_FORMAT=json
ENV WORKDIR=/

WORKDIR $WORKDIR

ADD docker-entrypoint.sh /
ADD etc/edgedns.toml /etc/edgedns.toml

# Check UDP port is open
HEALTHCHECK --interval=10s \
    --timeout=5s \
    --start-period=5s \
    --retries=3 \
    CMD netstat -nau | grep -w 5353 > /dev/null; if [ 0 != $? ]; then exit 1; fi;

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 5353/tcp
EXPOSE 5353/udp

CMD ["edgedns", "--config", "/etc/edgedns.toml"]
