name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mingc/edgedns

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $IMAGE_NAME:$GITHUB_SHA
    - name: Inspect the Docker image
      run: |
        docker images
        docker inspect $IMAGE_NAME:$GITHUB_SHA
    - name: Cleanup
      run: |
        docker rmi $IMAGE_NAME:$GITHUB_SHA
